import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  // ─── Global / Shared ───
  'close': { en: 'Close', fr: 'Fermer' },
  'back': { en: 'Back', fr: 'Retour' },
  'done': { en: 'Done', fr: 'Terminé' },
  'remove': { en: 'Remove', fr: 'Retirer' },
  'delete': { en: 'Delete', fr: 'Supprimer' },
  'save': { en: 'Save', fr: 'Enregistrer' },
  'cancel': { en: 'Cancel', fr: 'Annuler' },
  'retry': { en: 'Retry', fr: 'Réessayer' },
  'search': { en: 'Search', fr: 'Rechercher' },
  'loading': { en: 'Loading...', fr: 'Chargement...' },
  'today': { en: 'Today', fr: "Aujourd'hui" },
  'rep': { en: 'Rep', fr: 'Rép' },
  'reps': { en: 'Reps', fr: 'Reps' },
  'sets': { en: 'sets', fr: 'séries' },
  'set': { en: 'Set', fr: 'Série' },
  'form': { en: 'Form', fr: 'Forme' },
  'cal': { en: 'cal', fr: 'cal' },
  'kcal': { en: 'kcal', fr: 'kcal' },

  // ─── Tab bar / Navigation ───
  'home': { en: 'Home', fr: 'Accueil' },
  'nutrition': { en: 'Nutrition', fr: 'Nutrition' },
  'progress': { en: 'Progress', fr: 'Progrès' },
  'profile': { en: 'Profile', fr: 'Profil' },
  'train': { en: 'Train', fr: "S'entraîner" },

  // ─── Dashboard ───
  'tagline': { en: 'Your AI Gym Companion', fr: 'Votre coach fitness intelligent' },
  'ai_engine_ready': { en: 'AI Engine Ready', fr: 'Moteur IA prêt' },
  'engine_failed': { en: 'Engine Failed', fr: 'Moteur en erreur' },
  'loading_ai': { en: 'Loading AI...', fr: 'Chargement IA...' },
  'install_app': { en: 'Install WorkoutVision', fr: 'Installer WorkoutVision' },
  'install_desc': { en: 'Add to home screen for full app experience', fr: "Ajouter à l'écran d'accueil" },
  'install': { en: 'Install', fr: 'Installer' },
  'burned': { en: 'burned', fr: 'brûlées' },
  'kcal_eaten': { en: 'kcal eaten', fr: 'kcal ingérées' },
  'protein': { en: 'protein', fr: 'protéines' },
  'progressing': { en: 'Progressing', fr: 'En progression' },
  'needs_attention': { en: 'Needs attention', fr: 'À surveiller' },
  'plateau': { en: 'Plateau', fr: 'Plateau' },
  'd_streak': { en: 'd streak', fr: 'j. consécutifs' },
  'deload_warning': { en: 'Consider a deload week. Form scores declining over 4 weeks.', fr: 'Envisagez une semaine de décharge. Scores de forme en baisse depuis 4 semaines.' },
  'view_all_progressions': { en: 'View all progressions', fr: 'Voir toutes les progressions' },
  'nav_live': { en: 'LIVE', fr: 'DIRECT' },
  'nav_live_title': { en: 'Live Training', fr: 'Entraînement en direct' },
  'nav_live_desc': { en: 'Real-time form coaching with camera', fr: 'Coaching de forme en temps réel avec la caméra' },
  'nav_video': { en: 'VIDEO', fr: 'VIDÉO' },
  'nav_video_title': { en: 'Analyze Video', fr: 'Analyser une vidéo' },
  'nav_video_desc': { en: 'Upload and analyze recordings', fr: 'Importer et analyser des enregistrements' },
  'nav_id': { en: 'ID', fr: 'ID' },
  'nav_id_title': { en: 'Identify Machine', fr: 'Identifier une machine' },
  'nav_id_desc': { en: 'Photo a machine to find the exercise', fr: "Photographier une machine pour trouver l'exercice" },
  'nav_food': { en: 'FOOD', fr: 'REPAS' },
  'nav_food_title': { en: 'Log Nutrition', fr: 'Journal nutritionnel' },
  'nav_food_desc': { en: 'Scan barcode or photo your plate', fr: 'Scanner un code-barres ou photographier votre assiette' },
  'nav_plan': { en: 'PLAN', fr: 'PLAN' },
  'nav_plan_title': { en: 'My Plan', fr: 'Mon programme' },
  'nav_plan_desc': { en: 'Personalized workout plan & body analysis', fr: "Programme d'entraînement et analyse corporelle" },
  'nav_log': { en: 'LOG', fr: 'SAISIE' },
  'nav_log_title': { en: 'Manual Log', fr: 'Saisie manuelle' },
  'nav_log_desc': { en: 'Log sets without camera', fr: 'Enregistrer des séries sans caméra' },
  'nav_prs': { en: 'PRs', fr: 'PRs' },
  'nav_prs_title': { en: 'Exercise History', fr: 'Historique des exercices' },
  'nav_prs_desc': { en: 'All sets, PRs, and progress per exercise', fr: 'Séries, records et progression par exercice' },
  'nav_rest': { en: 'REST', fr: 'REPOS' },
  'nav_rest_title': { en: 'Rest Timer', fr: 'Minuteur de repos' },
  'nav_rest_desc': { en: 'Between-set countdown with audio alert', fr: 'Compte à rebours entre séries avec alerte sonore' },
  'setup_profile': { en: 'Set up your profile', fr: 'Configurer votre profil' },
  'setup_profile_desc': { en: 'Add your weight, height, age for personalized calories and macro targets', fr: 'Ajoutez poids, taille et âge pour des objectifs caloriques personnalisés' },
  'recent': { en: 'Recent', fr: 'Récent' },
  'form_colon': { en: 'Form:', fr: 'Forme :' },
  'what_makes_different': { en: 'What makes it different', fr: 'Ce qui fait la différence' },
  'step_1_desc': { en: 'Real-time pose detection with form coaching and voice cues', fr: 'Détection de posture en temps réel avec coaching vocal' },
  'step_2_desc': { en: 'Track nutrition: scan barcodes, photo plates, search 100+ foods', fr: 'Suivi nutritionnel : scanner, photographier, chercher plus de 100 aliments' },
  'step_3_desc': { en: 'Get science-backed progression and periodization recommendations', fr: 'Recommandations de progression et périodisation basées sur la science' },
  'diff_1': { en: 'Real-time pose detection with 33 body landmarks', fr: 'Détection de posture temps réel avec 33 points corporels' },
  'diff_2': { en: 'Per-rep form scoring and voice coaching', fr: 'Score de forme par répétition et coaching vocal' },
  'diff_3': { en: 'Velocity tracking for fatigue detection', fr: 'Suivi de vitesse pour détection de la fatigue' },
  'diff_4': { en: '55+ exercises with form analysis', fr: "Plus de 55 exercices avec analyse de la forme" },
  'diff_5': { en: 'Personalized nutrition and macro targets', fr: 'Objectifs nutritionnels et macros personnalisés' },
  'diff_6': { en: 'Periodized workout plans adapted to your goals', fr: "Programmes périodisés adaptés à vos objectifs" },

  // ─── Video Upload / Analyze ───
  'analyze_video': { en: 'Analyze Video', fr: 'Analyser la vidéo' },
  'tap_to_select': { en: 'Tap to select videos', fr: 'Appuyer pour sélectionner des vidéos' },
  'file_types': { en: 'MP4, MOV, WebM', fr: 'MP4, MOV, WebM' },
  'automatic': { en: 'Automatic', fr: 'Automatique' },
  'compound': { en: 'Compound', fr: 'Polyarticulaire' },
  'isolation': { en: 'Isolation', fr: 'Isolation' },
  'bodyweight': { en: 'Bodyweight', fr: 'Poids du corps' },
  'other': { en: 'Other', fr: 'Autre' },
  'analyze': { en: 'Analyze', fr: 'Analyser' },
  'failed_try_different': { en: 'Failed — try a different clip with better lighting or angle', fr: 'Échec — essayez un autre clip avec un meilleur éclairage ou angle' },
  'loading_ai_engine': { en: 'Loading AI engine...', fr: 'Chargement du moteur IA...' },
  'downloading_model': { en: 'Downloading pose detection model (~3 MB)', fr: 'Téléchargement du modèle de détection (~3 Mo)' },
  'loading_file': { en: 'Loading', fr: 'Chargement de' },
  'analyzing_file': { en: 'Analyzing', fr: 'Analyse de' },
  'starting_file': { en: 'Starting', fr: 'Démarrage de' },
  'auto_detected': { en: 'Auto-detected', fr: 'Détecté auto.' },
  'duration': { en: 'Duration', fr: 'Durée' },
  'quality': { en: 'Quality', fr: 'Qualité' },
  'analysis': { en: 'Analysis', fr: 'Analyse' },
  'velocity_per_rep': { en: 'Velocity per rep', fr: 'Vitesse par rep' },
  'time_under_tension': { en: 'Time under tension', fr: 'Temps sous tension' },
  'eccentric': { en: 'Eccentric', fr: 'Excentrique' },
  'concentric': { en: 'Concentric', fr: 'Concentrique' },
  'total': { en: 'Total', fr: 'Total' },
  'range_of_motion': { en: 'Range of motion', fr: 'Amplitude de mouvement' },
  'avg_rom': { en: 'Avg ROM', fr: 'ROM moy.' },
  'consistency': { en: 'Consistency', fr: 'Régularité' },
  'asymmetry': { en: 'Asymmetry', fr: 'Asymétrie' },
  'imbalance': { en: 'Imbalance', fr: 'Déséquilibre' },
  'fatigue': { en: 'Fatigue', fr: 'Fatigue' },
  'fatigue_index': { en: 'Fatigue index', fr: 'Indice de fatigue' },
  'velocity_dropoff': { en: 'Velocity dropoff', fr: 'Perte de vitesse' },
  'form_notes': { en: 'Form notes', fr: 'Notes de forme' },
  'engine': { en: 'Engine', fr: 'Moteur' },
  'highlights': { en: 'Highlights', fr: 'Points forts' },
  'next_steps': { en: 'Next steps', fr: 'Prochaines étapes' },
  'per_rep_quality': { en: 'Per-rep quality', fr: 'Qualité par rep' },
  'watch_overlay': { en: 'Watch with AI Overlay', fr: 'Voir avec superposition IA' },
  'share_card': { en: 'Share Summary Card', fr: 'Partager la fiche résumé' },
  'share_reel': { en: 'Share as Reel ▶', fr: 'Partager en Reel ▶' },
  'no_poses': { en: 'Could not detect any poses', fr: 'Aucune pose détectée' },
  'try_different': { en: 'Try a different angle or better lighting. Ensure your full body is visible.', fr: 'Essayez un autre angle ou un meilleur éclairage. Assurez-vous que tout le corps est visible.' },
  'model_failed': { en: "AI model failed to load. Check your connection.", fr: "Le modèle IA n'a pas pu se charger. Vérifiez votre connexion." },
  'video_failed': { en: 'Video failed to load. Try a different file or shorter clip.', fr: 'Échec du chargement vidéo. Essayez un autre fichier ou un clip plus court.' },
  'too_large': { en: 'is too large. Maximum is 500 MB.', fr: 'est trop volumineux. Maximum 500 Mo.' },
  'need_more_reps': { en: 'Need more reps.', fr: 'Plus de reps nécessaires.' },
  'joint_knee': { en: 'Knee', fr: 'Genou' },
  'joint_hip': { en: 'Hip', fr: 'Hanche' },
  'joint_elbow': { en: 'Elbow', fr: 'Coude' },
  'joint_shoulder': { en: 'Shoulder', fr: 'Épaule' },

  // ─── Video Replay ───
  'ai_overlay': { en: 'AI Overlay', fr: 'Superposition IA' },
  'download_hd': { en: 'Download HD Video', fr: 'Télécharger vidéo HD' },
  'save_screenshot': { en: 'Save HD Screenshot', fr: 'Enregistrer capture HD' },
  'exporting': { en: 'Exporting', fr: 'Export en cours' },
  'cancel_export': { en: 'Cancel Export', fr: "Annuler l'export" },

  // ─── Live Camera ───
  'live_training': { en: 'Live Training', fr: 'Entraînement en direct' },
  'start_set': { en: 'Start Set', fr: 'Démarrer série' },
  'stop_set': { en: 'Stop & Save', fr: 'Arrêter et sauver' },
  'rest_timer': { en: 'Rest Timer', fr: 'Minuteur de repos' },
  'skip_rest': { en: 'Skip', fr: 'Passer' },
  'next_set': { en: 'Next Set', fr: 'Série suivante' },
  'init_camera': { en: 'Initializing camera and model...', fr: 'Initialisation de la caméra et du modèle...' },
  'camera_failed': { en: "Camera or model failed to load.", fr: "Impossible de charger la caméra ou le modèle." },
  'move_into_frame': { en: 'Move into frame', fr: 'Placez-vous dans le cadre' },
  'no_pose_detected': { en: 'No pose detected', fr: 'Aucune posture détectée' },
  // downloading_model defined earlier at line ~99
  'starting_camera': { en: 'Starting camera...', fr: 'Démarrage de la caméra...' },
  'flip_camera': { en: 'Flip camera', fr: 'Retourner la caméra' },
  'slow_device_banner': { en: 'AI running slowly on this device. Skeleton hidden to save power.', fr: 'IA lente sur cet appareil. Squelette masqué pour économiser.' },
  'switch_manual': { en: 'Manual Log', fr: 'Saisie manuelle' },

  // ─── Coaching report (structured findings) ───
  'coach_no_exercises': { en: 'No exercises recorded in this session.', fr: 'Aucun exercice enregistré dans cette session.' },
  'coach_complete_one': { en: 'Complete at least one exercise to generate a report.', fr: 'Effectuez au moins un exercice pour générer un rapport.' },
  'coach_symmetry': { en: 'Excellent bilateral symmetry on {{exerciseName}}.', fr: 'Excellente symétrie bilatérale sur {{exerciseName}}.' },
  'coach_velocity_drop': { en: 'Velocity dropped {{dropoff}}% on {{exerciseName}}.', fr: 'Vitesse en baisse de {{dropoff}}% sur {{exerciseName}}.' },
  'coach_rom_inconsistent': { en: 'Inconsistent range of motion on {{exerciseName}} ({{consistency}}%).', fr: 'Amplitude irrégulière sur {{exerciseName}} ({{consistency}}%).' },
  'coach_compensation': { en: '{{pattern}} detected on {{exerciseName}}: {{description}}', fr: '{{pattern}} détecté sur {{exerciseName}} : {{description}}' },
  'coach_quality_strong': { en: 'Strong movement quality on {{exerciseName}} ({{score}}/100).', fr: 'Excellente qualité de mouvement sur {{exerciseName}} ({{score}}/100).' },
  'coach_good_volume': { en: 'Good volume on {{muscle}}: {{sets}} working sets.', fr: 'Bon volume sur {{muscle}} : {{sets}} séries de travail.' },
  'coach_session_completed': { en: 'Completed {{count}} exercise(s) this session.', fr: '{{count}} exercice(s) complété(s) cette session.' },
  'coach_no_issues': { en: 'No significant issues detected. Maintain current form and consider progressive overload.', fr: 'Aucun problème significatif détecté. Maintenez votre forme et envisagez une surcharge progressive.' },
  'coach_summary': { en: 'Session grade: {{grade}}. {{totalReps}} total reps across {{exerciseCount}} exercise(s). Volume: {{volumeLoad}} kg.', fr: 'Note de session : {{grade}}. {{totalReps}} répétitions au total sur {{exerciseCount}} exercice(s). Volume : {{volumeLoad}} kg.' },
  'detecting': { en: 'Detecting...', fr: 'Détection...' },
  'rest_label': { en: 'REST', fr: 'REPOS' },
  'seconds': { en: 'seconds', fr: 'secondes' },
  'voice_coach': { en: 'Voice coach', fr: 'Coach vocal' },
  'rest_x_s': { en: 'Rest', fr: 'Repos' },
  'sets_colon': { en: 'Sets:', fr: 'Séries :' },
  'burned_colon': { en: 'Burned:', fr: 'Brûlées :' },
  'exit_session': { en: 'Exit session?', fr: 'Quitter la session ?' },
  'superset_other': { en: 'Superset / Other', fr: 'Superset / Autre' },

  // ─── Voice coaching (spoken via TTS, session-locked language) ───
  'voice_rest': { en: 'Rest {{seconds}} seconds', fr: 'Repos {{seconds}} secondes' },
  'voice_next_set': { en: 'Time. Next set.', fr: 'Temps écoulé. Série suivante.' },
  'voice_set_complete': { en: '{{reps}} reps. Form score {{score}}. {{cal}} calories burned.', fr: '{{reps}} reps. Score {{score}}. {{cal}} calories brûlées.' },
  'model_download_progress': { en: 'Downloading model: {{percent}}%', fr: 'Téléchargement : {{percent}}%' },

  // ─── Profile ───
  'your_measurements': { en: 'Your measurements', fr: 'Vos mensurations' },
  'name': { en: 'Name', fr: 'Nom' },
  'age': { en: 'Age', fr: 'Âge' },
  'weight_kg': { en: 'Weight (kg)', fr: 'Poids (kg)' },
  'height_cm': { en: 'Height (cm)', fr: 'Taille (cm)' },
  'sex': { en: 'Sex', fr: 'Sexe' },
  'male': { en: 'Male', fr: 'Homme' },
  'female': { en: 'Female', fr: 'Femme' },
  'ethnicity': { en: 'Ethnicity', fr: 'Origine ethnique' },
  'activity_level': { en: 'Activity Level', fr: "Niveau d'activité" },
  'sedentary': { en: 'Sedentary', fr: 'Sédentaire' },
  'light_activity': { en: 'Light (1-2x/week)', fr: 'Léger (1-2x/sem.)' },
  'moderate_activity': { en: 'Moderate (3-4x/week)', fr: 'Modéré (3-4x/sem.)' },
  'active_activity': { en: 'Active (5-6x/week)', fr: 'Actif (5-6x/sem.)' },
  'very_active_activity': { en: 'Very Active (daily)', fr: 'Très actif (quotidien)' },
  'resting_hr': { en: 'Resting HR (bpm)', fr: 'FC repos (bpm)' },
  'experience': { en: 'Experience', fr: 'Expérience' },
  'beginner': { en: 'Beginner', fr: 'Débutant' },
  'intermediate': { en: 'Intermediate', fr: 'Intermédiaire' },
  'advanced': { en: 'Advanced', fr: 'Avancé' },
  'goal': { en: 'Goal', fr: 'Objectif' },
  'general_fitness': { en: 'General Fitness', fr: 'Forme générale' },
  'strength': { en: 'Strength', fr: 'Force' },
  'muscle_growth': { en: 'Muscle Growth', fr: 'Prise de muscle' },
  'endurance': { en: 'Endurance', fr: 'Endurance' },
  'weight_loss': { en: 'Weight Loss', fr: 'Perte de poids' },
  'injuries': { en: 'Injuries / limitations', fr: 'Blessures / limitations' },
  'save_profile': { en: 'Save Profile', fr: 'Enregistrer le profil' },
  'saved': { en: 'Saved!', fr: 'Enregistré !' },
  'your_baselines': { en: 'Your baselines', fr: 'Vos valeurs de référence' },
  'medical_records': { en: 'Medical records', fr: 'Dossier médical' },
  'upload_file': { en: 'Upload file', fr: 'Importer un fichier' },
  'file_too_large': { en: 'File too large. Maximum size is 10MB.', fr: 'Fichier trop volumineux. Taille maximale : 10 Mo.' },
  'hr_zones_title': { en: 'Heart rate zones', fr: 'Zones de fréquence cardiaque' },
  'daily_energy': { en: 'Daily energy needs', fr: 'Besoins énergétiques journaliers' },
  'strength_baselines': { en: 'Strength baselines (untrained est.)', fr: 'Bases de force (est. débutant)' },
  'est_bf': { en: 'Est. BF', fr: 'MG est.' },
  'max_hr_short': { en: 'Max HR', fr: 'FC max' },
  'upload_medical_desc': { en: 'Upload medical files. Everything stays on your device.', fr: 'Importez vos documents médicaux. Tout reste sur votre appareil.' },
  'pdf_images_docs': { en: 'PDF, images, documents', fr: 'PDF, images, documents' },
  'no_records_yet': { en: 'No records uploaded yet.', fr: 'Aucun document importé.' },
  'uploaded_on': { en: 'Uploaded', fr: 'Importé le' },
  'bmi': { en: 'BMI', fr: 'IMC' },
  'bmr': { en: 'BMR', fr: 'MB' },

  // ─── Onboarding ───
  'welcome_subtitle': { en: 'Your AI-powered fitness companion', fr: "Votre compagnon fitness propulsé par l'IA" },
  'get_started': { en: 'Get Started', fr: 'Commencer' },
  'skip': { en: 'Skip', fr: 'Passer' },
  'onb_step1_title': { en: 'Tell us about you', fr: 'Parlez-nous de vous' },
  'onb_step1_desc': { en: 'We personalize your experience based on your profile.', fr: 'Nous personnalisons votre expérience selon votre profil.' },
  'onb_step2_title': { en: 'Your goals', fr: 'Vos objectifs' },
  'onb_step2_desc': { en: 'Help us tailor your workout recommendations.', fr: 'Aidez-nous à adapter vos recommandations.' },
  'next': { en: 'Next', fr: 'Suivant' },
  'finish': { en: 'Finish', fr: 'Terminer' },
  'onb_feature_live': { en: 'Real-time form analysis', fr: 'Analyse de forme en temps réel' },
  'onb_feature_video': { en: 'Video upload analysis', fr: 'Analyse de vidéos importées' },
  'onb_feature_nutrition': { en: 'Nutrition tracking', fr: 'Suivi nutritionnel' },
  'onb_feature_progress': { en: 'Progress tracking', fr: 'Suivi de progression' },

  // ─── Progress / Workout History ───
  'no_workouts': { en: 'No workouts yet', fr: 'Aucun entraînement' },
  'no_workouts_desc': { en: 'Start a live session or upload a video to see your progress here.', fr: 'Lancez une session en direct ou importez une vidéo pour voir votre progression.' },
  'sessions': { en: 'Sessions', fr: 'Sessions' },
  'total_reps': { en: 'Total Reps', fr: 'Reps totales' },
  'avg_form': { en: 'Avg Form', fr: 'Forme moy.' },
  'day_streak': { en: 'Day Streak', fr: 'Jours consécutifs' },
  'form_score_trend': { en: 'Form score trend', fr: 'Tendance du score de forme' },
  'delete_workout_confirm': { en: 'Delete this workout?', fr: 'Supprimer cet entraînement ?' },
  'this_week': { en: 'This week', fr: 'Cette semaine' },
  'last_week': { en: 'Last week', fr: 'Semaine dernière' },
  'weeks_ago': { en: 'weeks ago', fr: 'semaines' },
  'video_tag': { en: '(video)', fr: '(vidéo)' },
  'live_tag': { en: '(live)', fr: '(direct)' },
  'workouts': { en: 'Workouts', fr: 'Entraînements' },
  'training_load': { en: 'Training load', fr: "Charge d'entraînement" },
  'optimal': { en: 'optimal', fr: 'optimal' },
  'oldest': { en: 'Oldest', fr: 'Ancien' },
  'latest': { en: 'Latest', fr: 'Récent' },
  'loading_workouts': { en: 'Loading workouts...', fr: 'Chargement des entraînements...' },
  'week_of': { en: 'Week of', fr: 'Semaine du' },

  // ─── Rest Timer ───
  'rest_timer_title': { en: 'Rest Timer', fr: 'Minuteur de repos' },
  'rests': { en: 'RESTS', fr: 'REPOS' },
  'ready': { en: 'READY', fr: 'PRÊT' },
  'custom': { en: 'Custom', fr: 'Personnalisé' },
  'seconds_max_600': { en: 'Seconds (max 600)', fr: 'Secondes (max 600)' },
  'reset': { en: 'Reset', fr: 'Réinitialiser' },
  'pause': { en: 'Pause', fr: 'Pause' },
  'restart': { en: 'Restart', fr: 'Reprendre' },
  'start': { en: 'Start', fr: 'Démarrer' },

  // ─── Manual Log ───
  'log_workout': { en: 'Log Workout', fr: 'Enregistrer un entraînement' },
  'select_exercise': { en: 'Select exercise...', fr: 'Choisir un exercice...' },
  'search_exercises': { en: 'Search exercises...', fr: 'Rechercher un exercice...' },
  'no_exercises_found': { en: 'No exercises found.', fr: 'Aucun exercice trouvé.' },
  'weight_kg_short': { en: 'Weight (kg)', fr: 'Poids (kg)' },
  'add_set': { en: '+ Add set', fr: '+ Ajouter une série' },
  'add_exercise': { en: '+ Add exercise', fr: '+ Ajouter un exercice' },
  'saving': { en: 'Saving...', fr: 'Enregistrement...' },
  'workout_saved': { en: 'Workout logged successfully.', fr: 'Entraînement enregistré.' },

  // ─── Machine Identifier ───
  'identify_machine': { en: 'Identify machine', fr: 'Identifier la machine' },
  'take_photo': { en: 'Take a photo', fr: 'Prendre une photo' },
  'browse_catalog': { en: 'Browse equipment catalog', fr: 'Parcourir le catalogue' },
  'how_it_works': { en: 'How it works', fr: 'Comment ça marche' },
  'step_photo': { en: 'Take a photo of the machine or yourself using it', fr: "Photographiez la machine ou vous en train de l'utiliser" },
  'step_detect': { en: 'AI detects the exercise from your pose', fr: "L'IA détecte l'exercice d'après votre posture" },
  'step_start': { en: 'Start tracking with the correct exercise', fr: "Commencez le suivi avec le bon exercice" },
  'analyzing_pose': { en: 'Analyzing pose...', fr: 'Analyse de la posture...' },
  'exercise_detected': { en: 'Exercise detected', fr: 'Exercice détecté' },
  'confidence': { en: 'Confidence:', fr: 'Confiance :' },
  'use_this_exercise': { en: 'Use this exercise', fr: 'Utiliser cet exercice' },
  'not_right_browse': { en: 'Not right? Browse catalog', fr: 'Incorrect ? Parcourir le catalogue' },
  'no_person_detected': { en: 'No person detected', fr: 'Aucune personne détectée' },
  'try_another_photo': { en: 'Try another photo', fr: 'Essayer une autre photo' },
  'search_machines': { en: 'Search machines or exercises...', fr: 'Chercher machines ou exercices...' },
  'select': { en: 'Select', fr: 'Sélectionner' },

  // ─── Exercise History ───
  'exercise_history': { en: 'Exercise History', fr: 'Historique des exercices' },
  'loading_history': { en: 'Loading history...', fr: "Chargement de l'historique..." },
  'personal_records': { en: 'Personal Records', fr: 'Records personnels' },
  'best_weight': { en: 'Best Weight', fr: 'Meilleur poids' },
  'most_reps': { en: 'Most Reps', fr: 'Max reps' },
  'best_form': { en: 'Best Form', fr: 'Meilleure forme' },
  'weight_progression': { en: 'Weight Progression', fr: 'Progression en poids' },
  'all_sets': { en: 'All Sets', fr: 'Toutes les séries' },
  'pr': { en: 'PR', fr: 'PR' },
  'no_exercises_recorded': { en: "No exercises recorded yet.", fr: "Aucun exercice enregistré." },
  'best_colon': { en: 'Best:', fr: 'Meilleur :' },
  'max_reps_colon': { en: 'Max reps:', fr: 'Max reps :' },
  'last_colon': { en: 'Last:', fr: 'Dernier :' },

  // ─── Nutrition ───
  'maintain': { en: 'Maintain', fr: 'Maintien' },
  'cut': { en: 'Cut (-500)', fr: 'Sèche (-500)' },
  'bulk': { en: 'Bulk (+300)', fr: 'Prise (+300)' },
  'target': { en: 'Target', fr: 'Objectif' },
  'eaten': { en: 'Eaten', fr: 'Ingéré' },
  'remaining': { en: 'remaining', fr: 'restant' },
  'over': { en: 'over', fr: 'en excès' },
  'macros': { en: 'Macros', fr: 'Macros' },
  'protein_cap': { en: 'Protein', fr: 'Protéines' },
  'carbs': { en: 'Carbs', fr: 'Glucides' },
  'fat': { en: 'Fat', fr: 'Lipides' },
  'search_food': { en: 'Search food', fr: 'Chercher un aliment' },
  'scan_barcode': { en: 'Scan barcode', fr: 'Scanner un code-barres' },
  'photo_plate': { en: 'Photo plate', fr: 'Photographier le plat' },
  'food_log': { en: 'Food log', fr: 'Journal alimentaire' },
  'no_food_logged_today': { en: "No food logged today", fr: "Aucun aliment enregistré aujourd'hui" },
  'no_food_logged_day': { en: 'No food logged this day', fr: 'Aucun aliment enregistré ce jour' },
  'food_log_empty_desc': { en: 'Search, scan a barcode, or photo your plate to start tracking.', fr: 'Cherchez, scannez un code-barres ou photographiez votre assiette pour commencer.' },
  'workout_burn': { en: 'Workout burn', fr: 'Dépense entraînement' },
  'add_food': { en: 'Add food', fr: 'Ajouter un aliment' },
  'amount_g': { en: 'Amount (g)', fr: 'Quantité (g)' },
  'meal': { en: 'Meal', fr: 'Repas' },
  'breakfast': { en: 'Breakfast', fr: 'Petit-déjeuner' },
  'lunch': { en: 'Lunch', fr: 'Déjeuner' },
  'dinner': { en: 'Dinner', fr: 'Dîner' },
  'snack': { en: 'Snack', fr: 'Collation' },
  'add_to': { en: 'Add to', fr: 'Ajouter au' },
  'quick_portions': { en: 'Quick portions', fr: 'Portions rapides' },
  'search_foods': { en: 'Search foods...', fr: 'Rechercher des aliments...' },
  'no_results': { en: 'No results found', fr: 'Aucun résultat' },
  'scanned_product': { en: 'Scanned product', fr: 'Produit scanné' },
  'nutri_score': { en: 'Nutri-Score', fr: 'Nutri-Score' },
  'scan_barcode_title': { en: 'Scan Barcode', fr: 'Scanner un code-barres' },
  'point_camera_barcode': { en: 'Point camera at a barcode', fr: 'Pointez la caméra vers un code-barres' },
  'barcode_not_supported': { en: 'Barcode scanning not supported in this browser.', fr: 'Scan de code-barres non supporté dans ce navigateur.' },
  'barcode_try_other': { en: 'Try Chrome or Edge on Android, or Safari 17+ on iOS.', fr: 'Essayez Chrome ou Edge sur Android, ou Safari 17+ sur iOS.' },
  'go_back': { en: 'Go back', fr: 'Retour' },
  'camera_denied': { en: "Camera access denied.", fr: "Accès à la caméra refusé." },
  'looking_up_product': { en: 'Looking up product...', fr: 'Recherche du produit...' },
  'photo_your_plate': { en: 'Photo your plate', fr: 'Photographiez votre assiette' },
  'take_photo_meal': { en: 'Take a photo of your meal', fr: 'Prenez une photo de votre repas' },
  'tap_open_camera': { en: 'Tap to open camera', fr: 'Appuyez pour ouvrir la caméra' },
  'photo_plate_desc': { en: 'Describe your meal and estimate the macros. Portion photos help you track consistency over time.', fr: 'Décrivez votre repas et estimez les macros. Les photos aident à suivre la régularité.' },
  'what_did_you_eat': { en: "What did you eat?", fr: "Qu'avez-vous mangé ?" },
  'meal_placeholder': { en: 'e.g. Grilled chicken with rice', fr: 'Ex. Poulet grillé avec riz' },
  'portion_g': { en: 'Portion (g)', fr: 'Portion (g)' },
  'calories_est': { en: 'Calories (est.)', fr: 'Calories (est.)' },
  'protein_g': { en: 'Protein (g)', fr: 'Protéines (g)' },
  'carbs_g': { en: 'Carbs (g)', fr: 'Glucides (g)' },
  'fat_g': { en: 'Fat (g)', fr: 'Lipides (g)' },
  'retake_photo': { en: 'Retake photo', fr: 'Reprendre la photo' },
  'delete_entry_confirm': { en: 'Delete this entry?', fr: 'Supprimer cette entrée ?' },

  // ─── Workout Plan ───
  'workout_plan': { en: 'Workout Plan', fr: "Programme d'entraînement" },
  'generating': { en: 'Generating...', fr: 'Génération...' },
  'building_plan': { en: 'Building your personalized plan', fr: 'Construction de votre programme personnalisé' },
  'no_profile_found': { en: 'No Profile Found', fr: 'Aucun profil trouvé' },
  'setup_profile_first': { en: 'Set up your profile first to get a personalized plan.', fr: 'Configurez votre profil pour obtenir un programme personnalisé.' },
  'go_to_profile': { en: 'Go to Profile', fr: 'Aller au profil' },
  'profile_incomplete_hint': { en: 'Add experience, goals, resting HR, and injuries in your profile for more accurate results.', fr: 'Ajoutez expérience, objectifs, FC repos et blessures dans votre profil pour plus de précision.' },
  'my_analysis': { en: 'My Analysis', fr: 'Mon analyse' },
  'key_stats': { en: 'Key Stats', fr: 'Statistiques clés' },
  'body_composition': { en: 'Body Composition', fr: 'Composition corporelle' },
  'est_body_fat': { en: 'Est. Body Fat', fr: 'Masse grasse est.' },
  'ideal_weight': { en: 'Ideal Weight', fr: 'Poids idéal' },
  'tdee': { en: 'TDEE', fr: 'DETT' },
  'hr_zones': { en: 'Heart Rate Zones', fr: 'Zones de fréquence cardiaque' },
  'max_hr': { en: 'Max HR:', fr: 'FC max :' },
  'resting': { en: 'Resting:', fr: 'Repos :' },
  'bpm': { en: 'bpm', fr: 'bpm' },
  'daily_targets': { en: 'Daily Targets', fr: 'Objectifs journaliers' },
  'calories': { en: 'Calories', fr: 'Calories' },
  'est_1rm': { en: 'Estimated 1RM Potential', fr: 'Potentiel 1RM estimé' },
  'squat': { en: 'Squat', fr: 'Squat' },
  'bench_press': { en: 'Bench Press', fr: 'Développé couché' },
  'deadlift': { en: 'Deadlift', fr: 'Soulevé de terre' },
  'recommendations': { en: 'Recommendations', fr: 'Recommandations' },
  'your_program': { en: 'Your Program', fr: 'Votre programme' },
  'days_week': { en: 'days/week', fr: 'jours/sem.' },
  'week_mesocycle': { en: 'week mesocycle:', fr: 'semaines mésocycle :' },
  'day': { en: 'Day', fr: 'Jour' },
  'rest_colon': { en: 'Rest:', fr: 'Repos :' },
  'recovery': { en: 'Recovery', fr: 'Récupération' },
  'aerobic': { en: 'Aerobic', fr: 'Aérobie' },
  'tempo': { en: 'Tempo', fr: 'Tempo' },
  'threshold': { en: 'Threshold', fr: 'Seuil' },
  'vo2max': { en: 'VO2max', fr: 'VO2max' },

  // ─── Medical Records ───
  'medical_records_title': { en: 'Medical Records', fr: 'Dossier médical' },
  'uploading': { en: 'Uploading...', fr: 'Importation...' },
  'upload_medical': { en: 'Upload medical records', fr: 'Importer un dossier médical' },
  'pdf_jpg_png': { en: 'PDF, JPG, PNG', fr: 'PDF, JPG, PNG' },
  'key_health_markers': { en: 'Key health markers to track', fr: 'Marqueurs de santé à suivre' },
  'uploaded_records': { en: 'Uploaded records', fr: 'Documents importés' },
  'pdf_document': { en: 'PDF document', fr: 'Document PDF' },
  'add_notes_record': { en: 'Add notes about this record...', fr: 'Ajouter des notes sur ce document...' },
  'uploaded': { en: 'Uploaded', fr: 'Importé le' },
  'marker_resting_hr': { en: 'Resting heart rate', fr: 'Fréquence cardiaque au repos' },
  'marker_blood_pressure': { en: 'Blood pressure (systolic/diastolic)', fr: 'Tension artérielle (systolique/diastolique)' },
  'marker_hba1c': { en: 'HbA1c', fr: 'HbA1c' },
  'marker_testosterone': { en: 'Testosterone', fr: 'Testostérone' },
  'marker_vitamin_d': { en: 'Vitamin D', fr: 'Vitamine D' },
  'marker_iron': { en: 'Iron / Ferritin', fr: 'Fer / Ferritine' },
  'marker_crp': { en: 'CRP (inflammation)', fr: 'CRP (inflammation)' },
  'marker_lipids': { en: 'Lipid panel (LDL, HDL, triglycerides)', fr: 'Bilan lipidique (LDL, HDL, triglycérides)' },
  'marker_injuries': { en: 'Injury history / notes', fr: 'Historique de blessures / notes' },

  // ─── Training load zones ───
  'zone_undertraining': { en: 'Undertraining', fr: 'Sous-entraînement' },
  'zone_optimal': { en: 'Optimal', fr: 'Optimal' },
  'zone_caution': { en: 'Caution', fr: 'Attention' },
  'zone_danger': { en: 'Danger', fr: 'Danger' },
  'unknown': { en: 'Unknown', fr: 'Inconnu' },

  // ─── Exercise names ───
  'ex.squat': { en: 'Barbell Back Squat', fr: 'Squat barre' },
  'ex.deadlift': { en: 'Deadlift', fr: 'Soulevé de terre' },
  'ex.bench_press': { en: 'Bench Press', fr: 'Développé couché' },
  'ex.overhead_press': { en: 'Overhead Press', fr: 'Développé militaire' },
  'ex.barbell_row': { en: 'Barbell Row', fr: 'Rowing barre' },
  'ex.bicep_curl': { en: 'Bicep Curl', fr: 'Curl biceps' },
  'ex.tricep_extension': { en: 'Tricep Extension', fr: 'Extension triceps' },
  'ex.lateral_raise': { en: 'Lateral Raise', fr: 'Élévation latérale' },
  'ex.front_raise': { en: 'Front Raise', fr: 'Élévation frontale' },
  'ex.romanian_deadlift': { en: 'Romanian Deadlift', fr: 'Soulevé de terre roumain' },
  'ex.leg_press': { en: 'Leg Press', fr: 'Presse à cuisses' },
  'ex.leg_extension': { en: 'Leg Extension (Machine)', fr: 'Extension de jambe machine' },
  'ex.leg_curl': { en: 'Leg Curl (Machine)', fr: 'Curl de jambe machine' },
  'ex.calf_raise': { en: 'Calf Raise', fr: 'Mollets debout' },
  'ex.pull_up': { en: 'Pull-Up', fr: 'Traction' },
  'ex.push_up': { en: 'Push-Up', fr: 'Pompe' },
  'ex.dip': { en: 'Dip', fr: 'Dips' },
  'ex.plank': { en: 'Plank', fr: 'Planche' },
  'ex.lunge': { en: 'Lunge', fr: 'Fente' },
  'ex.hip_thrust': { en: 'Hip Thrust', fr: 'Hip Thrust' },
  'ex.cable_fly': { en: 'Cable Fly', fr: 'Écarté poulie' },
  'ex.face_pull': { en: 'Face Pull', fr: 'Face Pull' },
  'ex.hammer_curl': { en: 'Hammer Curl', fr: 'Curl marteau' },
  'ex.skull_crusher': { en: 'Skull Crusher', fr: 'Barre au front' },
  'ex.upright_row': { en: 'Upright Row', fr: 'Rowing menton' },
  'ex.shrug': { en: 'Shrug', fr: "Haussement d'épaules" },
  'ex.chest_fly': { en: 'Chest Fly', fr: 'Écarté pectoraux' },
  'ex.incline_press': { en: 'Incline Press', fr: 'Développé incliné' },
  'ex.decline_press': { en: 'Decline Press', fr: 'Développé décliné' },
  'ex.seated_row': { en: 'Seated Row', fr: 'Rowing assis' },
  'ex.lat_pulldown': { en: 'Lat Pulldown', fr: 'Tirage vertical' },
  'ex.preacher_curl': { en: 'Preacher Curl', fr: 'Curl au pupitre' },
  'ex.concentration_curl': { en: 'Concentration Curl', fr: 'Curl concentration' },
  'ex.lying_bicep_curl': { en: 'Lying Bicep Curl', fr: 'Curl allongé' },
  'ex.spider_curl': { en: 'Spider Curl', fr: 'Spider curl' },
  'ex.cable_curl': { en: 'Cable Curl', fr: 'Curl poulie' },
  'ex.tricep_pushdown': { en: 'Tricep Pushdown', fr: 'Poussée triceps poulie' },
  'ex.overhead_tricep': { en: 'Overhead Tricep Extension', fr: 'Extension triceps au-dessus' },
  'ex.kickback': { en: 'Tricep Kickback', fr: 'Kickback triceps' },
  'ex.goblet_squat': { en: 'Goblet Squat', fr: 'Goblet squat' },
  'ex.bulgarian_split': { en: 'Bulgarian Split Squat', fr: 'Squat bulgare' },
  'ex.bulgarian_split_squat': { en: 'Bulgarian Split Squat', fr: 'Squat bulgare' },
  'ex.step_up': { en: 'Step-Up', fr: 'Step-up' },
  'ex.good_morning': { en: 'Good Morning', fr: 'Good morning' },
  'ex.sumo_deadlift': { en: 'Sumo Deadlift', fr: 'Soulevé sumo' },
  'ex.hack_squat': { en: 'Hack Squat', fr: 'Hack squat' },
  'ex.sit_up': { en: 'Sit-Up', fr: 'Abdos' },
  'ex.crunch': { en: 'Crunch', fr: 'Crunch' },
  'ex.mountain_climber': { en: 'Mountain Climber', fr: 'Mountain climber' },
  'ex.burpee': { en: 'Burpee', fr: 'Burpee' },
  'ex.jumping_jack': { en: 'Jumping Jack', fr: 'Jumping jack' },
  'ex.box_jump': { en: 'Box Jump', fr: 'Box jump' },
  'ex.superset': { en: 'Superset / Other', fr: 'Superset / Autre' },

  // ─── Exercise names (missing FR translations) ───
  'ex.front_squat': { en: 'Front Squat', fr: 'Squat avant' },
  'ex.standing_leg_extension': { en: 'Standing Leg Extension', fr: 'Extension de jambe debout' },
  'ex.bent_over_row': { en: 'Bent-Over Row', fr: 'Rowing penché' },
  'ex.chest_supported_row': { en: 'Chest-Supported Row', fr: 'Rowing poitrine appuyée' },
  'ex.machine_chest_press': { en: 'Machine Chest Press', fr: 'Presse pectoraux machine' },
  'ex.pike_push_up': { en: 'Pike Push-Up', fr: 'Pompe pike' },
  'ex.diamond_push_up': { en: 'Diamond Push-Up', fr: 'Pompe diamant' },
  'ex.inverted_row': { en: 'Inverted Row', fr: 'Rowing inversé' },
  'ex.jump_squat': { en: 'Jump Squat', fr: 'Squat sauté' },
  'ex.pistol_squat': { en: 'Pistol Squat', fr: 'Squat pistol' },
  'ex.glute_bridge': { en: 'Glute Bridge', fr: 'Pont fessier' },
  'ex.wall_sit': { en: 'Wall Sit', fr: 'Chaise murale' },
  'ex.dead_hang': { en: 'Dead Hang', fr: 'Suspension passive' },
  'ex.l_sit': { en: 'L-Sit Hold', fr: 'L-sit' },
  'ex.hollow_body_hold': { en: 'Hollow Body Hold', fr: 'Hollow body' },
  'ex.overhead_hold': { en: 'Overhead Hold', fr: 'Maintien au-dessus' },
  'ex.side_plank': { en: 'Side Plank', fr: 'Planche latérale' },
  'ex.kettlebell_swing': { en: 'Kettlebell Swing', fr: 'Swing kettlebell' },
  'ex.thruster': { en: 'Thruster', fr: 'Thruster' },
  'ex.clean_and_press': { en: 'Clean and Press', fr: 'Épaulé-jeté' },
  'ex.renegade_row': { en: 'Renegade Row', fr: 'Rowing renegade' },
  'ex.turkish_get_up': { en: 'Turkish Get-Up', fr: 'Relevé turc' },
  'ex.bear_crawl': { en: 'Bear Crawl', fr: 'Marche de l\'ours' },
  'ex.muscle_up': { en: 'Muscle-Up', fr: 'Muscle-up' },
  'ex.chin_up': { en: 'Chin-Up', fr: 'Traction supination' },
  'ex.skater_jump': { en: 'Skater Jump', fr: 'Saut patineur' },
  'ex.squat_jump_to_lunge': { en: 'Squat Jump to Lunge', fr: 'Squat sauté en fente' },
  'ex.man_maker': { en: 'Man Maker', fr: 'Man maker' },
  'ex.commando_pull_up': { en: 'Commando Pull-Up', fr: 'Traction commando' },
  'ex.incline_bench_press': { en: 'Incline Bench Press', fr: 'Développé incliné' },
  'ex.nordic_curl': { en: 'Nordic Curl', fr: 'Curl nordique' },
  'ex.seated_calf_raise': { en: 'Seated Calf Raise', fr: 'Mollets assis' },
  'ex.hanging_leg_raise': { en: 'Hanging Leg Raise', fr: 'Relevé de jambes suspendu' },
  'ex.smith_squat': { en: 'Smith Machine Squat', fr: 'Squat Smith machine' },
  'ex.zercher_squat': { en: 'Zercher Squat', fr: 'Squat Zercher' },
  'ex.overhead_squat': { en: 'Overhead Squat', fr: 'Squat overhead' },
  'ex.power_clean': { en: 'Power Clean', fr: 'Épaulé puissance' },
  'ex.snatch': { en: 'Snatch', fr: 'Arraché' },
  'ex.t_bar_row': { en: 'T-Bar Row', fr: 'Rowing T-bar' },
  'ex.pendlay_row': { en: 'Pendlay Row', fr: 'Rowing Pendlay' },
  'ex.close_grip_bench': { en: 'Close-Grip Bench', fr: 'Développé couché prise serrée' },
  'ex.decline_bench_press': { en: 'Decline Bench Press', fr: 'Développé décliné' },
  'ex.floor_press': { en: 'Floor Press', fr: 'Développé au sol' },
  'ex.landmine_press': { en: 'Landmine Press', fr: 'Presse landmine' },
  'ex.arnold_press': { en: 'Arnold Press', fr: 'Développé Arnold' },
  'ex.cable_tricep_pushdown': { en: 'Cable Tricep Pushdown', fr: 'Poussée triceps poulie' },
  'ex.rear_delt_fly': { en: 'Rear Delt Fly', fr: 'Oiseau arrière épaule' },
  'ex.dumbbell_fly': { en: 'Dumbbell Fly', fr: 'Écarté haltères' },
  'ex.cable_crossover': { en: 'Cable Crossover', fr: 'Crossover poulie' },
  'ex.wrist_curl': { en: 'Wrist Curl', fr: 'Curl poignet' },
  'ex.v_up': { en: 'V-Up', fr: 'V-up' },
  'ex.russian_twist': { en: 'Russian Twist', fr: 'Rotation russe' },
  'ex.bicycle_crunch': { en: 'Bicycle Crunch', fr: 'Crunch pédalage' },
  'ex.flutter_kick': { en: 'Flutter Kick', fr: 'Battement de jambes' },
  'ex.superman': { en: 'Superman', fr: 'Superman' },
  'ex.hand_release_push_up': { en: 'Hand Release Push-Up', fr: 'Pompe mains décollées' },
  'ex.wide_push_up': { en: 'Wide Push-Up', fr: 'Pompe large' },
  'ex.archer_push_up': { en: 'Archer Push-Up', fr: 'Pompe archer' },
  'ex.incline_push_up': { en: 'Incline Push-Up', fr: 'Pompe inclinée' },
  'ex.deficit_push_up': { en: 'Deficit Push-Up', fr: 'Pompe déficit' },
  'ex.deficit_push_down': { en: 'Deficit Push-Down', fr: 'Pompe déclinée déficit' },
  'ex.toes_to_bar': { en: 'Toes to Bar', fr: 'Orteils à la barre' },
  'ex.single_leg_deadlift': { en: 'Single-Leg Deadlift', fr: 'Soulevé de terre unipodal' },
  'ex.reverse_lunge': { en: 'Reverse Lunge', fr: 'Fente arrière' },
  'ex.walking_lunge': { en: 'Walking Lunge', fr: 'Fente marchée' },
  'ex.side_lunge': { en: 'Side Lunge', fr: 'Fente latérale' },
  'ex.split_jerk': { en: 'Split Jerk', fr: 'Jeté fente' },
  'ex.push_press': { en: 'Push Press', fr: 'Push press' },
  'ex.wall_ball': { en: 'Wall Ball', fr: 'Wall ball' },
  'ex.battle_rope': { en: 'Battle Rope', fr: 'Corde ondulatoire' },

  // ─── Velocity trend keys ───
  'trend_stable': { en: 'stable', fr: 'stable' },
  'trend_fatigue': { en: 'declining (fatigue)', fr: 'en baisse (fatigue)' },
  'trend_declining': { en: 'slightly declining', fr: 'légère baisse' },
  'trend_warmup': { en: 'increasing (warm-up)', fr: 'en hausse (échauffement)' },
  'trend_insufficient': { en: 'insufficient data', fr: 'données insuffisantes' },

  // ─── Fatigue recommendations ───
  'fatigue_significant': { en: 'Significant fatigue detected across the set.', fr: 'Fatigue importante détectée sur la série.' },
  'fatigue_moderate': { en: 'Moderate fatigue. Good for hypertrophy (Pareja-Blanco 2017).', fr: 'Fatigue modérée. Bon pour l\'hypertrophie (Pareja-Blanco 2017).' },
  'fatigue_low': { en: 'Low fatigue. Good for strength without excessive fatigue.', fr: 'Fatigue faible. Bon pour la force sans fatigue excessive.' },
  'fatigue_warmup_effect': { en: 'Velocity increased through the set. Warm-up effect detected.', fr: 'Vitesse en hausse durant la série. Effet d\'échauffement détecté.' },
  'fatigue_minimal': { en: 'Minimal fatigue. Could increase intensity or volume.', fr: 'Fatigue minimale. Vous pouvez augmenter l\'intensité ou le volume.' },
  'fatigue_no_data': { en: 'Need more data.', fr: 'Données insuffisantes.' },

  // ─── Session note ───
  'session_total': { en: '{{count}} reps total across {{exercises}} exercises', fr: '{{count}} répétitions au total sur {{exercises}} exercices' },

  // ─── Coaching insights ───
  'insight_rom_drop': { en: 'Range of motion dropped {{drop}}% across the set.', fr: 'Amplitude diminuée de {{drop}}% pendant la série.' },
  'insight_fatigue': { en: 'Reps slowed {{drop}}% toward the end. Fatigue detected.', fr: 'Ralentissement de {{drop}}% vers la fin. Fatigue détectée.' },
  'insight_asymmetry': { en: 'Left/right imbalance of {{score}}% detected.', fr: 'Déséquilibre gauche/droite de {{score}}% détecté.' },
  'insight_too_fast': { en: 'Eccentric phase was faster than concentric across the set.', fr: 'Phase excentrique plus rapide que la concentrique sur la série.' },
  'insight_ready_progress': { en: 'All reps stayed within 15% of each other. Consistent set.', fr: 'Toutes les répétitions dans un écart de 15%. Série constante.' },
  'insight_best_rep': { en: 'Rep {{num}} scored highest.', fr: 'Répétition {{num}} a obtenu le meilleur score.' },

  // ─── Progression notes ───
  'prog_rom_up': { en: '+{{change}}° ROM improvement vs {{date}}.', fr: "+{{change}}° d'amplitude gagnée vs {{date}}." },
  'prog_rom_down': { en: '{{change}}° ROM decrease vs {{date}}.', fr: "{{change}}° d'amplitude perdue vs {{date}}." },
  'prog_form_up': { en: 'Form improved vs {{date}} (+{{change}} points).', fr: 'Forme améliorée vs {{date}} (+{{change}} points).' },
  'prog_form_down': { en: 'Form dropped vs {{date}}.', fr: 'Forme en baisse vs {{date}}.' },
  'prog_consistent': { en: 'Consistent with last session ({{date}}).', fr: 'Constant par rapport à la dernière session ({{date}}).' },
  'yesterday': { en: 'yesterday', fr: 'hier' },
  'days_ago': { en: '{{n}} days ago', fr: 'il y a {{n}} jours' },

  // ─── Diagnostics / misc ───
  'trend': { en: 'Trend', fr: 'Tendance' },
  'diag_range': { en: 'Range', fr: 'Plage' },
  'diag_min_rom': { en: 'Min ROM per rep', fr: "Amplitude min par rép" },
  'diag_frames': { en: 'Frames', fr: 'Images' },
  'diag_method': { en: 'Method', fr: 'Méthode' },
  'limitations': { en: 'Limitations', fr: 'Limitations' },

  // ─── Insights section ───
  'insights_title': { en: 'Your Insights', fr: 'Vos analyses' },
  'body_profile': { en: 'Body Profile', fr: 'Profil corporel' },
  'bmi': { en: 'BMI', fr: 'IMC' },
  'body_fat_est': { en: 'Body Fat (est.)', fr: 'Masse grasse (est.)' },
  'max_hr': { en: 'Max HR', fr: 'FC max' },
  'bpm': { en: 'bpm', fr: 'bpm' },
  'strength_levels': { en: 'Strength Levels', fr: 'Niveaux de force' },
  'no_weighted': { en: 'Log exercises with weight to see strength levels.', fr: 'Enregistrez des exercices avec poids pour voir vos niveaux.' },
  'estimated_1rm': { en: 'Est. 1RM', fr: '1RM est.' },
  'training_load': { en: 'Training Load', fr: 'Charge d\'entraînement' },
  'workload_ratio': { en: 'Workload Ratio', fr: 'Ratio de charge' },
  'zone_optimal': { en: 'Optimal', fr: 'Optimal' },
  'zone_undertraining': { en: 'Undertraining', fr: 'Sous-entraînement' },
  'zone_caution': { en: 'Caution', fr: 'Attention' },
  'zone_danger': { en: 'Danger', fr: 'Danger' },
  'recovery': { en: 'Recovery', fr: 'Récupération' },
  'recovery_ready': { en: 'Recovered — ready to train', fr: 'Récupéré — prêt à s\'entraîner' },
  'recovery_partial': { en: 'Mostly recovered', fr: 'Presque récupéré' },
  'recovery_rest': { en: 'Rest needed', fr: 'Repos nécessaire' },
  'next_workout': { en: 'Suggested Next', fr: 'Prochaine séance' },
  'goal_tips': { en: 'Tips for Your Goal', fr: 'Conseils pour votre objectif' },
  'weekly_sets': { en: 'Weekly Sets', fr: 'Séries/semaine' },
  'no_workouts_yet': { en: 'Start logging workouts to see insights.', fr: 'Commencez à enregistrer vos séances pour voir vos analyses.' },
  'novice': { en: 'Novice', fr: 'Novice' },
  'elite': { en: 'Elite', fr: 'Élite' },
  'edit_profile': { en: 'Edit Profile', fr: 'Modifier le profil' },
  'saved': { en: 'Saved', fr: 'Enregistré' },
};

// ─── Form check message translations (bad/good strings from exercises.js) ───
// Keyed by the exact English string. Falls back to English if no French found.
const formCheckFr = {
  // Common across many exercises
  'Go deeper': 'Descendre plus bas',
  'Full depth achieved': 'Bonne profondeur',
  'Full extension': 'Extension complète',
  'Full lockout at top': 'Verrouillage complet en haut',
  'Extend fully at top': 'Extension complète en haut',
  'Extend fully at bottom': 'Extension complète en bas',
  'Extend fully': 'Extension complète',
  'Body in straight line': 'Corps aligné',
  'Torso upright': 'Torse droit',
  'Torso stable': 'Torse stable',
  'Torso upright throughout': 'Torse droit tout au long',
  'Torso vertical': 'Torse vertical',
  'Knees tracking over toes': 'Genoux alignés avec les orteils',
  'Knees tracking evenly': 'Genoux se déplaçant de façon symétrique',
  'Arms working evenly': 'Bras travaillant de façon symétrique',
  'Both arms pulling evenly': 'Les deux bras tirent de façon égale',
  'Both arms pressing evenly': 'Les deux bras poussent de façon égale',
  'Shoulders pressing evenly': 'Épaules poussant de façon égale',
  // Squat family
  'Below parallel': 'En dessous du parallèle',
  'Above parallel -- sit deeper': 'Au-dessus du parallèle — descendre plus bas',
  'Knee cave detected -- push knees out': 'Valgus du genou — poussez les genoux vers l\'extérieur',
  'Asymmetric knee bend': 'Flexion asymétrique des genoux',
  'Asymmetric knee bend -- check for lateral shift': 'Flexion asymétrique — vérifier le déplacement latéral',
  'Excessive forward lean': 'Inclinaison excessive vers l\'avant',
  'Excessive forward lean -- chest up': 'Inclinaison excessive — relevez la poitrine',
  'Leaning forward -- keep weight close to chest': 'Inclinaison — gardez le poids près de la poitrine',
  'Squat deeper': 'Descendre plus bas en squat',
  'Squat deeper before jumping': 'Squat plus profond avant de sauter',
  'Good squat depth before jump': 'Bonne profondeur de squat avant le saut',
  'Stay more upright': 'Rester plus droit',
  // Deadlift / hinge
  'Deep hip hinge achieved': 'Bonne charnière de hanche',
  'Deep hip hinge at bottom': 'Bonne charnière en bas',
  'Hinge deeper -- push hips back': 'Charnière plus profonde — poussez les hanches en arrière',
  'Hinge deeper -- push hips further back': 'Charnière plus profonde — poussez les hanches plus en arrière',
  'Hinge deeper at the hips': 'Charnière plus profonde aux hanches',
  'Back angle within safe range': 'Angle du dos dans la zone sûre',
  'Back rounding or insufficient hinge': 'Dos arrondi ou charnière insuffisante',
  'Back flat through hinge': 'Dos plat pendant la charnière',
  'Flat back maintained': 'Dos plat maintenu',
  'Neutral spine at lockout': 'Colonne neutre au verrouillage',
  'Excessive trunk rounding -- maintain neutral spine': 'Arrondissement excessif — maintenez une colonne neutre',
  'Full hip extension at top': 'Extension complète des hanches en haut',
  'Full hip extension -- glutes fully engaged': 'Extension complète — fessiers engagés',
  'Incomplete lockout -- squeeze glutes at top': 'Verrouillage incomplet — serrez les fessiers',
  'Full hip snap at top': 'Extension explosive des hanches en haut',
  'Knees slightly bent -- soft lock maintained': 'Genoux légèrement fléchis — verrouillage souple',
  'Knees too bent or too locked -- slight bend protects hamstrings': 'Genoux trop fléchis ou trop verrouillés — légère flexion protège les ischio-jambiers',
  // Hip thrust / bridge
  'Full hip extension -- peak glute contraction': 'Extension complète — contraction maximale des fessiers',
  'Incomplete extension -- squeeze at the top': 'Extension incomplète — serrez en haut',
  'Knee angle ~90 deg at top': 'Angle du genou ~90° en haut',
  'Reposition feet -- knees should be ~90 deg at lockout': 'Repositionner les pieds — genoux à ~90° au verrouillage',
  'Anterior pelvic tilt detected -- tuck pelvis and brace abs at the top': 'Antéversion du bassin — rentrez le bassin et gaineze en haut',
  // Bench / press
  'Bar touching upper chest': 'Barre touchant le haut de la poitrine',
  'Lower the bar further -- touch upper chest': 'Descendre la barre — toucher le haut de la poitrine',
  'Lock out fully at top': 'Verrouillage complet en haut',
  'Lock out fully': 'Verrouiller complètement',
  'Press to full lockout': 'Pousser jusqu\'au verrouillage complet',
  'Press to full extension': 'Pousser jusqu\'à l\'extension complète',
  // Push-up
  'Full depth -- chest near floor': 'Bonne profondeur — poitrine près du sol',
  'Go deeper -- elbows to 90 deg or below': 'Descendre plus — coudes à 90° ou en dessous',
  'Body rigid and straight': 'Corps rigide et aligné',
  'Hips sagging or piking -- maintain straight line': 'Hanches qui s\'affaissent ou remontent — maintenir la ligne',
  'Hips sagging or piking -- brace core': 'Hanches qui s\'affaissent — gainez',
  // Pull-up / row
  'Chin above bar': 'Menton au-dessus de la barre',
  'Chin above bar level': 'Menton au niveau de la barre',
  'Pull higher -- chin over bar': 'Tirer plus haut — menton au-dessus de la barre',
  'Full dead hang': 'Suspension complète',
  'Full dead hang at bottom': 'Suspension complète en bas',
  'Extend arms fully at bottom': 'Bras tendus en bas',
  'Start from a full hang': 'Partir d\'une suspension complète',
  'Full pull -- elbows past torso': 'Tirage complet — coudes au-delà du torse',
  'Pull further -- squeeze shoulder blades': 'Tirer plus — serrez les omoplates',
  'Full pull -- shoulder blades squeezed': 'Tirage complet — omoplates serrées',
  'Bar at chest -- full lat contraction': 'Barre à la poitrine — contraction complète des dorsaux',
  'Pull lower -- bar should reach upper chest': 'Tirer plus bas — barre au niveau de la poitrine',
  'Full contraction -- elbows pulled past torso': 'Contraction complète — coudes au-delà du torse',
  'Trunk hinged at proper angle': 'Torse incliné à l\'angle correct',
  'Maintain 45-degree forward lean': 'Maintenir 45° d\'inclinaison',
  'Keep torso closer to horizontal': 'Garder le torse plus horizontal',
  // Bicep curl
  'Curl higher -- full contraction': 'Monter plus haut — contraction complète',
  'Curl higher -- squeeze at peak': 'Monter plus haut — serrez au sommet',
  'Full bicep squeeze at top': 'Contraction complète du biceps en haut',
  'Full extension at bottom': 'Extension complète en bas',
  'Extend fully at bottom -- no half reps': 'Extension complète — pas de demi-répétitions',
  'Body swinging -- reduce weight or brace': 'Balancement du corps — réduisez le poids ou gainez',
  'No swinging -- isolate the bicep': 'Pas de balancement — isolez le biceps',
  'No swinging -- keep torso still': 'Pas de balancement — gardez le torse immobile',
  'Keep elbows pinned to sides': 'Gardez les coudes collés au corps',
  'Keep elbows pinned -- no flaring': 'Gardez les coudes fixes — pas d\'écartement',
  'Elbows stable and aligned': 'Coudes stables et alignés',
  // Tricep extension
  'Full stretch at top': 'Étirement complet en haut',
  'Deep stretch -- long head fully lengthened': 'Étirement profond — longue portion étirée',
  'Lower further behind head for full stretch': 'Descendre plus derrière la tête pour étirement complet',
  'Full extension at top': 'Extension complète en haut',
  'Full extension -- peak contraction': 'Extension complète — contraction maximale',
  'Elbows flaring -- keep them close to head': 'Coudes qui s\'écartent — gardez-les près de la tête',
  // Lateral / front raise
  'Arms at or above shoulder height': 'Bras au niveau des épaules ou au-dessus',
  'Raise higher -- at least to shoulder level': 'Monter plus — au moins au niveau des épaules',
  'Both arms at same height': 'Les deux bras à la même hauteur',
  'Uneven raise -- one arm lagging': 'Élévation inégale — un bras en retard',
  'Shoulders down -- clean isolation': 'Épaules basses — isolation propre',
  'Shrugging -- depress shoulders and reduce weight': 'Haussement — abaissez les épaules et réduisez le poids',
  // Leg extension / curl
  'Full knee extension -- peak quad contraction': 'Extension complète du genou — contraction maximale des quadriceps',
  'Extend fully -- squeeze quads at top': 'Extension complète — serrez les quadriceps en haut',
  'Full curl -- heels to glutes': 'Curl complet — talons vers les fessiers',
  'Curl further -- bring heels closer to glutes': 'Monter plus — rapprochez les talons des fessiers',
  'Both legs extending evenly': 'Les deux jambes s\'étendent de façon égale',
  // Dip
  'Full depth -- 90 deg knee angle': 'Bonne profondeur — angle de 90°',
  'Go deeper -- aim for 90 deg knee bend': 'Descendre plus — visez 90° de flexion',
  // Plank
  'Body in straight line from knee to shoulder': 'Corps aligné du genou à l\'épaule',
  'Hips sagging -- maintain plank position': 'Hanches qui s\'affaissent — maintenir la planche',
  'Hips rising -- keep back flat': 'Hanches qui remontent — garder le dos plat',
  'Hips dropping -- squeeze glutes and brace abs': 'Hanches qui descendent — serrez les fessiers et gainez',
  'Hips level': 'Hanches de niveau',
  'Lift hips -- maintain straight line': 'Lever les hanches — maintenir la ligne droite',
  // Calf raise
  'Knees straight -- gastrocnemius targeted': 'Genoux tendus — gastrocnémien ciblé',
  'Keep slight bend in knees': 'Garder une légère flexion des genoux',
  // Lunge
  'Rear knee approaching floor': 'Genou arrière proche du sol',
  'Drop knee lower': 'Descendre le genou plus bas',
  'Go deeper -- rear knee should approach the ground': 'Descendre plus — le genou arrière doit s\'approcher du sol',
  'Leaning forward -- stay tall': 'Inclinaison — restez droit',
  'Stay tall -- avoid leaning forward': 'Restez droit — évitez de pencher en avant',
  'Trunk upright and stable': 'Torse droit et stable',
  // Shrug
  'Pull elbows higher -- to shoulder level': 'Monter les coudes — au niveau des épaules',
  'Pull elbows higher -- squeeze shoulder blades': 'Monter les coudes — serrez les omoplates',
  'Keep arms straight -- shrug with traps only': 'Gardez les bras tendus — haussement avec les trapèzes uniquement',
  // Face pull
  'Elbows high and flared -- rear delts engaged': 'Coudes hauts et écartés — deltoïdes postérieurs engagés',
  'Elbows pulled high': 'Coudes tirés en haut',
  // General
  'Controlled movement -- no momentum': 'Mouvement contrôlé — pas d\'élan',
  'Strict form -- no swinging': 'Forme stricte — pas de balancement',
  'Swinging detected -- slow down and use control': 'Balancement détecté — ralentissez et contrôlez',
  'Excessive back lean -- reduce weight or brace harder': 'Inclinaison arrière excessive — réduisez le poids ou gainez plus',
  'Excessive leaning -- keep torso still': 'Inclinaison excessive — gardez le torse immobile',
  'Sit upright -- avoid leaning forward': 'Asseyez-vous droit — évitez de pencher en avant',
  'Upright seated posture': 'Posture assise droite',
  'Soft landing -- knees absorbing impact': 'Atterrissage souple — genoux absorbant l\'impact',
  'Land softer -- absorb with legs': 'Atterrir plus doucement — absorbez avec les jambes',
  'Full standing extension at top': 'Extension debout complète en haut',
  'Stand up fully between reps': 'Se redresser complètement entre les reps',
  'Drive hips through -- full extension': 'Poussez les hanches — extension complète',
  'Push hips higher -- full extension': 'Poussez les hanches plus haut — extension complète',
  'Knees soft -- not squatting the swing': 'Genoux souples — ne pas squatter le swing',
  'Less knee bend -- this is a hinge, not a squat': 'Moins de flexion des genoux — c\'est une charnière, pas un squat',
  'Upright torso maintained': 'Torse droit maintenu',
  'One arm lagging -- equalize': 'Un bras en retard — égalisez',
  'One arm pulling harder -- equalize': 'Un bras tire plus fort — égalisez',
  'One arm doing more work -- equalize': 'Un bras travaille plus — égalisez',
  'Uneven press -- one leg pushing harder': 'Poussée inégale — une jambe pousse plus',
  'One leg weaker -- balance out': 'Une jambe plus faible — équilibrez',
};

// ─── Detect initial language ───
function detectLang() {
  try {
    const saved = localStorage.getItem('wv_lang');
    if (saved === 'en' || saved === 'fr') return saved;
  } catch (_) {}
  if (typeof navigator !== 'undefined') {
    const bl = (navigator.language || navigator.userLanguage || 'en').toLowerCase();
    if (bl.startsWith('fr')) return 'fr';
  }
  return 'en';
}

// ─── React Context ───
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    const detected = detectLang();
    try { document.documentElement.lang = detected; } catch (_) {}
    return detected;
  });

  const setLang = useCallback((newLang) => {
    if (newLang !== 'en' && newLang !== 'fr') return;
    setLangState(newLang);
    try { localStorage.setItem('wv_lang', newLang); } catch (_) {}
    try { document.documentElement.lang = newLang; } catch (_) {}
  }, []);

  const t = useCallback((key, params) => {
    const entry = translations[key];
    if (!entry) return key;
    let str = entry[lang] || entry.en || key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        if (k === 'key') continue;
        str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), v ?? '');
      }
    }
    return str;
  }, [lang]);

  const tExercise = useCallback((exerciseKey, fallbackName) => {
    const key = `ex.${exerciseKey}`;
    const entry = translations[key];
    if (entry && entry[lang]) return entry[lang];
    return fallbackName || exerciseKey;
  }, [lang]);

  const tFormCheck = useCallback((englishStr) => {
    if (lang === 'en' || !englishStr) return englishStr;
    return formCheckFr[englishStr] || englishStr;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tExercise, tFormCheck }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useT() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useT must be used within LanguageProvider');
  return ctx;
}

// Module-level t() for non-React code (canvas overlays, utilities).
// Reads directly from localStorage so it stays in sync.
export function tModule(key, params) {
  let lang = 'en';
  try {
    const saved = localStorage.getItem('wv_lang');
    if (saved === 'en' || saved === 'fr') lang = saved;
  } catch (_) {}
  const entry = translations[key];
  if (!entry) return key;
  let str = entry[lang] || entry.en || key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      if (k === 'key') continue;
      str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), v ?? '');
    }
  }
  return str;
}
