// The words of the collection on David's phone (phoneCollect.js, CollectHistory.jsx), in one place for his approval
// (R10; test/real-phone/swarm/copy-collect.md lists them). Register: vous.
export const COLLECT = {
  fr: {
    on: 'Collecte activée sur ce téléphone : chaque série gardée garde aussi son fichier de repères.',
    off: 'Collecte désactivée sur ce téléphone.',
    failed: 'Ce téléphone n’a pas pu enregistrer le réglage de la collecte.',
    title: 'Séries collectées',
    none: 'Aucune série collectée pour l’instant.',
    send: n => `Envoyer les séries collectées (${n})`,
    shareTitle: 'Séries collectées',
    shared: n => `${n} ${n > 1 ? 'séries partagées' : 'série partagée'}. Les effacer de ce téléphone ?`,
    downloaded: n => `${n > 1 ? `${n} fichiers téléchargés` : 'Fichier téléchargé'}. Les effacer de ce téléphone ?`,
    clear: 'Effacer',
    keep: 'Garder',
    cleared: 'Séries collectées effacées de ce téléphone.',
    kept: 'Les séries restent sur ce téléphone.',
    shareFailed: 'Le partage n’a pas abouti. Touchez à nouveau pour télécharger.',
    readFailed: 'Les séries collectées n’ont pas pu être lues. Rouvrez vos séries pour réessayer.',
    clearFailed: 'Les séries n’ont pas pu être effacées. Réessayez.',
  },
  en: {
    on: 'Collection is on for this phone: each set you keep also keeps its landmark file.',
    off: 'Collection is off for this phone.',
    failed: 'This phone could not store the collection setting.',
    title: 'Collected sets',
    none: 'No collected set yet.',
    send: n => `Send collected sets (${n})`,
    shareTitle: 'Collected sets',
    shared: n => `${n} ${n === 1 ? 'set' : 'sets'} shared. Clear them from this phone?`,
    downloaded: n => `${n === 1 ? 'File' : `${n} files`} downloaded. Clear them from this phone?`,
    clear: 'Clear',
    keep: 'Keep',
    cleared: 'Collected sets cleared from this phone.',
    kept: 'The sets stay on this phone.',
    shareFailed: 'Sharing did not go through. Tap again to download.',
    readFailed: 'The collected sets could not be read. Open your sets again to retry.',
    clearFailed: 'The sets could not be cleared. Try again.',
  },
};
